version: "3.9"

services:
    java_app:
      container_name: java_app
      image: interview:1.0.0
      build: .
      ports:
        - 8080:8080
      environment:
        - DATABASE_URL=jdbc:postgresql://localhost:5432/Interview
        - DATABASE_USERNAME=postgres
        - DTABASE_PASWORD=postgres
      depends on:
        - java_db
    java_db:
      container_name: java_db
      image: postgres:12
      ports:
        -5432:5432
      enironment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: Interview